### ISSUE TITLE
SQL Error when attempting to create users or groups

### ISSUE THREAD

**Issue by Elpho910** [itmicus/cmdbuild_docker#38]
Receive the following error when running openmaint-2.3-3.4.1-d through docker compose when trying to create users or groups (potentially more but this is all I have tested and received the same error on so far)

org.cmdbuild.dao.DaoException: error executing insert for entry = CardImpl{id=null, type=User}, caused by: org.springframework.dao.DataIntegrityViolationException: StatementCallback; ERROR: null value in column "CurrentId" violates not-null constraint

**Comment by afcarvalho1991** [comment]
You are, most likely, leaving blank fields that should not be blank ... the problem with openmaint is this you do not get valuable feedback to fix your issues.

**Comment by mikegking** [comment]
I'm seeing the same thing with cmdbuild ready2use with demo db:

````org.cmdbuild.dao.DaoException: error executing insert for entry = CardImpl{id=null, code=1234, type=Supplier}, caused by: org.springframework.dao.DataIntegrityViolationException: StatementCallback; ERROR: null value in column "CurrentId" violates not-null constraint
Detail: Failing row contains (8022, "Supplier", 1234, dsflgkid, null, null, 2023-03-10 22:51:14.985482+00, null, null, null, null, 158, 40a, 1234, Somewhere, 123446, yes@no.com, https://www.google.com, 70).; nested exception is org.postgresql.util.PSQLException: ERROR: null value in column "CurrentId" violates not-null constraint
Detail: Failing row contains (8022, "Supplier", 1234, dsflgkid, null, null, 2023-03-10 22:51:14.985482+00, null, null, null, null, 158, 40a, 1234, Somewhere, 123446, yes@no.com, https://www.google.com, 70)., caused by: org.postgresql.util.PSQLException: ERROR: null value in column "CurrentId" violates not-null constraint
Detail: Failing row contains (8022, "Supplier", 1234, dsflgkid, null, null, 2023-03-10 22:51:14.985482+00, null, null, null, null, 158, 40a, 1234, Somewhere, 123446, yes@no.com, https://www.google.com, 70).

**Comment by afcarvalho1991** [comment]
We are able to create users and groups on our own project. I'll have a look at it tomorrow.

Please Wait a few hours

**Comment by teamz-adolfo** [comment]
Hi,

same problem here and I have fixed it changing PostgreSQL version in docker-compose.yml to **postgres:13.11-alpine3.18**.

```
version: "2.4"
volumes:
    cmdbuild-db:
    cmdbuild-tomcat:

services:
    cmdbuild_db:
        image: postgres:13.11-alpine3.18
        container_name: cmdbuild_db
        volumes:
            - cmdbuild-db:/var/lib/postgresql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=FvAz2evk7q8w5sEo
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=FvAz2evk7q8w5sEo
        restart: always
        mem_limit: 1000m
        mem_reservation: 300m

    cmdbuild_app:
        image: afcarvalho1991/cmdbuild:app-3.4.1
        container_name: cmdbuild_app
        links:
           - cmdbuild_db
        depends_on:
           - cmdbuild_db
        ports:
            - 8090:8080
        restart: always
        volumes:
            - cmdbuild-tomcat:/usr/local/tomcat
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=FvAz2evk7q8w5sEo
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=cmdbuild_db
            - POSTGRES_DB=cmdbuild_zabalit
            - JAVA_OPTS=-Xmx4000m -Xms2000m
        mem_limit: 4000m
        mem_reservation: 2000m
```

After that, there are no errors during the startup and the creation of new registers works as expected.

**Comment by infeeeee** [comment]
I had the same problem, but with OpenMaint. Using a newer official [postgis](https://hub.docker.com/r/postgis/postgis) image instead of `cmdbuild:db-3.0` did the trick. OpenMaint docs recommends postgres 12 only.

My docker-compose:

```yaml
version: "3.3"
volumes:
    openmaint-db:
    openmaint-tomcat:

services:
    openmaint_db:
        image: postgis/postgis:12-3.3-alpine
        container_name: openmaint_db
        volumes:
            - openmaint-db:/var/lib/postgresql
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=*****
        restart: always

    openmaint_app:
        image: afcarvalho1991/cmdbuild:om-2.3-3.4.1-d
        container_name: openmaint_app
        links:
           - openmaint_db
        depends_on:
           - openmaint_db
        ports:
            - 8090:8080
        restart: always
        volumes:
            - openmaint-tomcat:/usr/local/tomcat
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=*****
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=openmaint_db
            - POSTGRES_DB=openmaint
            - CMDBUILD_DUMP=empty.dump.xz
            - JAVA_OPTS=-Xmx4000m -Xms2000m
```
